language: python
sudo: false
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "pypy"
  - "pypy3"

env:
  - RL=30
  - RL=31
  - RL=32
  - RL=33
  - RL=34

matrix:
  fast_finish: true
  allow_failures:
    - python: "3.7-dev"
    - python: "pypy3"

install:
  - TOX_ENV=py${TRAVIS_PYTHON_VERSION}-rl${RL}
  - pip install tox coveralls Sphinx sphinx-rtd-theme nose

script: tox -e $TOX_ENV
after_success: coveralls $COVERALLS_OPTION

notifications:
  irc: "chat.freenode.net#xhtml2pdf"

before_script:
  - cd doc/source ; sphinx-build -nW -b html -d _build/doctrees . _build/html ; cd ../..
